# Generated by Django 4.2.20 on 2025-05-05 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='study',
            name='reaction',
        ),
    ]
