# Generated by Django 4.2.20 on 2025-05-05 16:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_delete_user_remove_study_reaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='association',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 5, 16, 47, 31, 345526, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='association',
            name='font_size',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='association',
            name='font_style',
            field=models.CharField(choices=[('normal', 'Прямой'), ('italic', 'Курсив'), ('oblique', 'Наклонный')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='association',
            name='font_weight',
            field=models.IntegerField(choices=[(100, 'Thin'), (400, 'Regular'), (600, 'Semi-Bold'), (700, 'Bold'), (900, 'Black')], default=400),
        ),
        migrations.AddField(
            model_name='association',
            name='letter_spacing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='association',
            name='line_height',
            field=models.DecimalField(decimal_places=1, default=1.5, max_digits=3),
        ),
        migrations.AlterField(
            model_name='association',
            name='cipher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='mainapp.cipher'),
        ),
        migrations.AlterField(
            model_name='association',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cipher',
            name='result',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='association',
            constraint=models.UniqueConstraint(fields=('user', 'cipher', 'font_weight', 'font_style', 'letter_spacing', 'font_size', 'line_height'), name='unique_user_font_variation_reaction'),
        ),
    ]
