# Generated by Django 4.2.20 on 2025-05-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_association_options_association_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='reaction_description',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
