# Generated by Django 4.2.20 on 2025-05-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_association_reaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='reaction_lemmas',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
